### PR TITLE
Up arrow for repeating rule ids

### PR DESCRIPTION
**Pull request by jamestalmage**
screenshot 2016-04-30 17 56 35

screenshot 2016-04-30 17 56 59

screenshot 2016-04-30 17 58 09

I think I like the last one the best.

Includes the change to gray from #6, so I'll need to rebase if we merge that. This has extra comment lines that need to be deleted anyways after we decide on an arrow.

### CODE REVIEW

**Comment by jamestalmage** [comment]
I would guess the up-arrow won't work on Windows, so just use `^`?

**Comment by jamestalmage** [comment]
Also, I think I've changed my mind and like the first arrow better. In some terminals (i.e. WebStorms built in terminal), the outlined arrow is hard to see.

**Comment by sindresorhus** [comment]
I'm not sure about this. Having an arrow, while less repetition, makes the output look unbalanced.

**Comment by sindresorhus** [comment]
@jamestalmage Do you still want this?

Here's a realistic output:

```
test/cli.js:99:3
⚠   99:3  Unexpected todo comment.  no-warning-comments
⚠  144:3  Unexpected todo comment.  ↑
⚠  144:3  Some other thing.         foo-bar
⚠  144:3  Another thing too.        unicorn-rainbow
⚠  144:3  Another thing too.        ↑
⚠  144:3  Another thing too.        ↑
```

Quite messy and less readable IMHO.

-

// @kevva @SamVerschueren Opinions?

**Comment by SamVerschueren** [comment]
I'm a little more in favour of repeating everything to be honest.

**Pull request closed without merging**
